### ISSUE TITLE
Update from Beta.1 to Beta.3 on System3 fails

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/hermes#104]
2023-07-03 16:28:14.134 UTC+2 - message-communication   - DEBUG         - put config message into the message queue
2023-07-03 16:28:15.700 UTC+2 - main                    - INFO          - checking for new config messages
2023-07-03 16:28:15.778 UTC+2 - configuration-procedure - DEBUG         - removing old .venv at path "/home/pi/Documents/hermes/0.1.0-beta.3/.venv"
2023-07-03 16:28:16.092 UTC+2 - configuration-procedure - INFO          - successfully removed all old .venvs
2023-07-03 16:28:16.092 UTC+2 - main                    - INFO          - running configuration procedure
2023-07-03 16:28:16.316 UTC+2 - configuration-procedure - INFO          - upgrading to revision 14
2023-07-03 16:28:16.374 UTC+2 - configuration-procedure - INFO          - using config {
    "version": "0.1.0-beta.3",
    "hardware": {
        "pumped_litres_per_round": 0.000833
    },
    "heated_enclosure": {
        "target_temperature": 25,
        "allowed_deviation": 3,
        "seconds_per_stored_datapoint": 60
    },
    "active_components": {
        "run_calibration_procedures": false,
        "send_messages_over_mqtt": true,
        "communicate_with_heated_enclosure": false,
        "run_pump_speed_monitoring": false,
        "ignore_missing_air_inlet_sensor": false
    },
    "calibration": {
        "timing": {
            "start_timestamp": 1682503200,
            "hours_between_calibrations": 25,
            "seconds_per_gas_bottle": 600
        },
        "gases": [
            {
                "valve_number": 2,
                "bottle_id": "991"
            },
            {
                "valve_number": 3,
                "bottle_id": "992"
            }
        ]
    },
    "verbose_logging": false,
    "measurement": {
        "timing": {
            "seconds_per_measurement_interval": 120,
            "seconds_per_measurement": 10,
            "pumped_litres_per_minute": 0.5
        },
        "air_inlets": [
            {
                "valve_number": 1,
                "direction": 0,
                "tube_length": 50
            }
        ]
    },
    "revision": 14
}
2023-07-03 16:28:16.374 UTC+2 - configuration-procedure - INFO          - code directory already exists
2023-07-03 16:28:16.375 UTC+2 - configuration-procedure - INFO          - setting up new venv
2023-07-03 16:28:24.349 UTC+2 - configuration-procedure - INFO          - installing dependencies
2023-07-03 16:29:41.502 UTC+2 - configuration-procedure - EXCEPTION     - upgrading to revision {new_revision}: exception during upgrade, src.utils.functions.CommandLineException: "command 'source .venv/bin/activate && poetry install' failed with exit code 1"
--- details: -----------------
stderr:

stout:
Installing dependencies from lock file

Package operations: 43 installs, 1 update, 0 removals

  • Installing adafruit-circuitpython-busdevice (5.2.4)
  • Installing adafruit-circuitpython-requests (1.13.1)
  • Installing idna (3.4)
  • Installing pyserial (3.5)
  • Installing pyusb (1.2.1)
  • Installing sniffio (1.3.0)
  • Installing typing-extensions (4.4.0)
  • Installing adafruit-circuitpython-typing (1.9.1)
  • Installing adafruit-platformdetect (3.45.1)
  • Installing adafruit-pureio (1.1.10)
  • Installing attrs (22.2.0)
  • Installing anyio (3.6.2)
  • Installing certifi (2022.12.7)
  • Installing h11 (0.14.0)
  • Installing exceptiongroup (1.1.0)
  • Installing iniconfig (2.0.0)
  • Installing packaging (23.0)
  • Installing pluggy (1.0.0)
  • Installing pyftdi (0.54.0)
  • Updating setuptools (44.1.1 -> 67.2.0)
  • Installing tomli (2.0.1)
  • Installing adafruit-blinka (8.18.1)
  • Installing colorzero (2.0)
  • Installing httpcore (0.16.3)
  • Installing ordered-set (4.1.0)
  • Installing orjson (3.8.5)
  • Installing pytest (7.2.1)
  • Installing pytz (2022.7.1)
  • Installing rfc3986 (1.5.0)

  RuntimeError

  Hash for adafruit-blinka (8.18.1) from archive Adafruit_Blinka-8.18.1-py3-none-any.whl not found in known hashes (was: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855)

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:673 in _validate_archive_hash
      669│         archive_hash: str = "sha256:" + get_file_hash(archive)
      670│         known_hashes = {f["hash"] for f in package.files}
      671│ 
      672│         if archive_hash not in known_hashes:
    → 673│             raise RuntimeError(
      674│                 f"Hash for {package} from archive {archive.name} not found in"
      675│                 f" known hashes (was: {archive_hash})"
      676│             )
      677│ 

  • Installing smbus2 (0.4.2)
--- traceback: ---------------
Traceback (most recent call last):

  File "/home/pi/Documents/hermes/0.1.0-beta.1/src/procedures/configuration.py", line 106, in run
    self._set_up_venv(new_version)

  File "/home/pi/Documents/hermes/0.1.0-beta.1/src/procedures/configuration.py", line 193, in _set_up_venv
    utils.run_shell_command(

  File "/home/pi/Documents/hermes/0.1.0-beta.1/src/utils/functions.py", line 41, in run_shell_command
    raise CommandLineException(

src.utils.functions.CommandLineException: "command 'source .venv/bin/activate && poetry install' failed with exit code 1"
------------------------------

**Comment by patrickjaigner** [comment]
Sorry, found a solution now: rm -rf ~/.cache/pypoetry

As seen here: https://stackoverflow.com/questions/71001968/python-poetry-install-failure-invalid-hashes
