### ISSUE TITLE
MQTT client fails to handle empty configuration message

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/hermes#107]
Sending queue reports to be full. No further info in the logs.

Before the issue, I pushed a new configuration with the newly implemented routes. The received configuration was reported to be {}, but was not initialized. 

```
sensor_identifier, name = get_station_info(station_number)

response = httpx.post(
    url=f"{BASE}/networks/{network_identifier}/sensors/{sensor_identifier}/configurations",
    headers={"authorization": f"Bearer {access_token}"},
    json={
        "sensor_name": name,
        "configuration": config
    }
)
pp(response)
```

Time: 10.07.2023 14:40
System: 1

Tried to fix it with a restart of hermes via the cli. Didn't help-

[2023-07-10.log](https://github.com/tum-esm/hermes/files/12002085/2023-07-10.log)

**Comment by patrickjaigner** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/pi/Documents/hermes/dev-hermes/sensor/src/procedures/mqtt_agent.py", line 285, in _f
    custom_types.MQTTConfigurationRequest(**json.loads(msg.payload.decode()))
  File "/home/pi/Documents/hermes/dev-hermes/sensor/.venv/lib/python3.9/site-packages/pydantic/main.py", line 342, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for MQTTConfigurationRequest
configuration -> version
  field required (type=value_error.missing)
