### ISSUE TITLE
Disconnected Wind Sensor lead to error restart

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/hermes#124]
2023-10-16 14:52:10.465 UTC+2 - wind-sensor             - WARNING       - last wind measurement data is older than 2 minutes
2023-10-16 14:52:10.468 UTC+2 - main                    - EXCEPTION     - exception in mainloop, src.hardware.wind_sensor.WindSensorInterface.DeviceFailure: last wind measurement data is older than 15 minutes
--- details: -----------------
None
--- traceback: ---------------
Traceback (most recent call last):

  File "/home/pi/Documents/hermes/0.2.0-beta.5/src/main.py", line 225, in run
    system_check_prodecure.run()

  File "/home/pi/Documents/hermes/0.2.0-beta.5/src/procedures/system_check.py", line 104, in run
    self.hardware_interface.check_errors()

  File "/home/pi/Documents/hermes/0.2.0-beta.5/src/hardware/__init__.py", line 59, in check_errors
    self.wind_sensor.check_errors()

  File "/home/pi/Documents/hermes/0.2.0-beta.5/src/hardware/wind_sensor.py", line 114, in check_errors
    raise WindSensorInterface.DeviceFailure(

src.hardware.wind_sensor.WindSensorInterface.DeviceFailure: last wind measurement data is older than 15 minutes
------------------------------
2023-10-16 14:52:10.498 UTC+2 - main                    - INFO          - performing hard reset
2023-10-16 14:52:10.519 UTC+2 - hardware-interface      - INFO          -

**Comment by patrickjaigner** [comment]
Fixed with 0.2.2-beta.3
