### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/hermes#184]
Observed on System 3 on 2 April. The system is permanently offline. 

```
ERROR main - exception during hard reset of hardware, BrokenPipeError: [Errno 32] Broken pipe --- details: -----------------
None
--- traceback: ---------------
Traceback (most recent call last):

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/input_devices.py", line 85, in __init__
    self.pin.function = 'input'

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/__init__.py", line 263, in <lambda>
    lambda self, value: self._set_function(value),

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/pigpio.py", line 228, in _set_function
    self.factory.connection.set_mode(self.number, self.GPIO_FUNCTIONS[value])

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/pigpio.py", line 1376, in set_mode
    return _u2i(_pigpio_command(self.sl, _PI_CMD_MODES, gpio, mode))

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/pigpio.py", line 1025, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))

BrokenPipeError: [Errno 32] Broken pipe


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/hardware/ups.py", line 108, in update_ups_status
    self._read_power_mode()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/hardware/ups.py", line 42, in _read_power_mode
    power_mode = gpiozero.DigitalInputDevice(

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/devices.py", line 108, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/input_devices.py", line 165, in __init__
    super(DigitalInputDevice, self).__init__(

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/mixins.py", line 218, in __init__
    super(EventsMixin, self).__init__(*args, **kwargs)

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/input_devices.py", line 90, in __init__
    self.close()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/mixins.py", line 240, in close
    super(EventsMixin, self).close()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/devices.py", line 568, in close
    self._pin.close()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/pigpio.py", line 218, in close
    self.function = 'input'

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/__init__.py", line 263, in <lambda>
    lambda self, value: self._set_function(value),

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/pigpio.py", line 228, in _set_function
    self.factory.connection.set_mode(self.number, self.GPIO_FUNCTIONS[value])

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/pigpio.py", line 1376, in set_mode
    return _u2i(_pigpio_command(self.sl, _PI_CMD_MODES, gpio, mode))

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/pigpio.py", line 1025, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))

BrokenPipeError: [Errno 32] Broken pipe


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/utils/functions.py", line 104, in get_gpio_pin_factory
    pin_factory = gpiozero.pins.pigpio.PiGPIOFactory(host="127.0.0.1")

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/pigpio.py", line 101, in __init__
    raise IOError('failed to connect to %s:%s' % (host, port))

OSError: failed to connect to 127.0.0.1:8888


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/main.py", line 149, in run
    system_check_prodecure.run()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/procedures/system_check.py", line 85, in run
    self.hardware_interface.ups.update_ups_status()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/hardware/ups.py", line 113, in update_ups_status
    self.pin_factory = utils.get_gpio_pin_factory()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/utils/functions.py", line 108, in get_gpio_pin_factory
    raise ConnectionError(

ConnectionError: pigpio is not connected, please run "sudo pigpiod -n 127.0.0.1"


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/main.py", line 275, in run
    hardware_interface.teardown()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/hardware/__init__.py", line 71, in teardown
    self.wind_sensor.teardown()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/src/hardware/wind_sensor.py", line 164, in teardown
    self.power_pin.off()

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/output_devices.py", line 111, in off
    self._write(False)

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/output_devices.py", line 96, in _write
    self.pin.state = self._value_to_state(value)

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/__init__.py", line 285, in <lambda>
    lambda self, value: self._set_state(value),

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/pigpio.py", line 249, in _set_state
    elif self.function == 'input':

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/__init__.py", line 262, in <lambda>
    lambda self: self._get_function(),

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/gpiozero/pins/pigpio.py", line 222, in _get_function
    return self.GPIO_FUNCTION_NAMES[self.factory.connection.get_mode(self.number)]

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/pigpio.py", line 1402, in get_mode
    return _u2i(_pigpio_command(self.sl, _PI_CMD_MODEG, gpio, 0))

  File "/home/pi/Documents/hermes/0.2.2-beta.5/.venv/lib/python3.9/site-packages/pigpio.py", line 1025, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))

BrokenPipeError: [Errno 32] Broken pipe
------------------------------
```

**Comment by larsfroelich** [comment]
looks like an issue with the connection between the hermes-sensor code and pigpio

**Comment by patrickjaigner** [comment]
It's a one-time issue. It hasn't happened again since the last restart fix. It will be closed.
