### ISSUE TITLE
Server responds with status 500 on too many parallel requests

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/hermes#68]
When I try to fetch logs and aggregates for all 20 sensors (40 requests) in parallel, the server responds with a 500 for some of them.

```log
[server] [2023-04-14 15:21:47] Fri 2023-04-14 15:21:47 +0000 | ERROR    | remaining connection slots are reserved for non-replication superuser connections
[server] [2023-04-14 15:21:47] Traceback (most recent call last):
[server] [2023-04-14 15:21:47]   File "/./app/main.py", line 289, in read_measurements
[server] [2023-04-14 15:21:47]     result = await dbpool.fetch(query, *arguments)
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 590, in fetch
[server] [2023-04-14 15:21:47]     async with self.acquire() as con:
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 998, in __aenter__
[server] [2023-04-14 15:21:47]     self.connection = await self.pool._acquire(self.timeout)
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 838, in _acquire
[server] [2023-04-14 15:21:47]     return await _acquire_impl()
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 823, in _acquire_impl
[server] [2023-04-14 15:21:47]     proxy = await ch.acquire()  # type: PoolConnectionProxy
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 137, in acquire
[server] [2023-04-14 15:21:47]     await self.connect()
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 129, in connect
[server] [2023-04-14 15:21:47]     self._con = await self._pool._get_new_connection()
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 521, in _get_new_connection
[server] [2023-04-14 15:21:47]     con = await connect_utils._connect_addr(
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
[server] [2023-04-14 15:21:47]     return await __connect_addr(params, timeout, True, *args)
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr
[server] [2023-04-14 15:21:47]     await compat.wait_for(connected, timeout=timeout)
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/site-packages/asyncpg/compat.py", line 56, in wait_for
[server] [2023-04-14 15:21:47]     return await asyncio.wait_for(fut, timeout)
[server] [2023-04-14 15:21:47]   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
[server] [2023-04-14 15:21:47]     return fut.result()
[server] [2023-04-14 15:21:47] asyncpg.exceptions.TooManyConnectionsError: remaining connection slots are reserved for non-replication superuser connections
[server] [2023-04-14 15:21:47] INFO:     10.244.2.22:39048 - "GET /sensors/fcce393d-ac53-4b59-ae71-d89cc2cdd619/measurements HTTP/1.1" 500 Internal Server Error
```

**Comment by empicano** [comment]
This is a deployment problem, not a problem in the code, I think. The error should be appropriately handled nonetheless 👍
